### PR TITLE
Update 404 

### PR DESCRIPTION
**Pull request by awesomelewis2007**
I added some JS to your 404 page so now it tells you what page your on 
`Sorry, The page: /example.html doesn't exist!`

### CODE REVIEW

**Review by Erisa — COMMENTED** [review]
Seems like unncessary JS addition for the sake of a fact that can already be seen by glancing at the address bar.

**Comment by awesomelewis2007** [comment]
> Seems like unncessary JS addition for the sake of a fact that can already be seen by glancing at the address bar.
Well,
image

**Comment by awesomelewis2007** [comment]
This just tells the user that that page doesn't exist without looking at the address bar

**Comment by Erisa** [comment]
Well with all due respect, Google likely does it with server-side code, making it client-side when not necessary causes (Among other things) an awful flashing animation for little tangible benefit (Especially on a personal website, where these things matter little)

But that said it's not exactly my site I'm just providing my view on it

14 Jun 2021 19:31:33 awesomelewis2007 ***@***.***>:

**Comment by awesomelewis2007** [comment]
mm ok

**Comment by awesomelewis2007** [comment]
i also made the pull request have a better formatting
@Erisa @goldsolitude

**Comment by goldsolitude** [comment]
Hi, thanks for the pull request but sorry I'm not interested in merging it, as I'd like to stay as close to @Erisa's upstream site (https://github.com/Erisa/erisa.moe) as possible. Also that I share the same opinions as her in that I don't really see the point in it at the moment especially for a basic static site.

**Comment by awesomelewis2007** [comment]
:(

**Pull request closed without merging**
